import { db } from '../db.js';
import { sha256 } from '../canonical.js';
import { narratorVoiceId, resolveVoiceId, dialogueLeadIn } from './casting.js';
import { setVoiceActive } from './audioDirector.js';
import { tollRefusal } from '../../patron/tollNotice.js';

// ------------------------------------------------------------
// THE NARRATOR — the interactive-podcast voice. Each turn is read
// as a CAST performance: the storyteller narrator reads the prose
// and frames each line, then each character's OWN voice speaks
// their dialogue (never the narrator reading "Name: line"). The
// segments are generated by the server speak chain (ElevenLabs →
// mock), cached in Dexie per segment+voice, and played in sequence.
// One turn plays at a time; a monotonic session token drops any
// generation that resolves after a newer request so two voices can
// never overlap. THE SOUND LAW: the voice stands alone — there is
// no music bed, nothing plays underneath it, and a segment of mock
// provenance is never played at all (the keyless floor for audio
// is silence, not placeholder tones). The narrator reports its
// activity to the Audio Director so music and effects yield the
// stage. A tiny pub/sub lets per-turn buttons reflect play/pause.
// This bypasses the Foundry tier gate on purpose: hearing the
// story read aloud is a comfort setting at any media tier.
// ------------------------------------------------------------

// Break a turn into an ordered list of voiced segments. Narration (no speaker)
// is the narrator's; a line of dialogue becomes a short narrator lead-in that
// names the speaker, then the character's own voice reading only the line.
// Consecutive same-voice segments are merged so the narrator's stage-setting and
// its hand-off ("…and that is when Halvard said,") are one smooth clip.
export function narrationSegments(dm, cast = []) {
  const blocks = (dm?.narration_blocks || []).filter((block) => block && block.text);
  const raw = [];
  blocks.forEach((block, i) => {
    if (!block.speaker) {
      raw.push({ voiceId: narratorVoiceId(), speaker: null, text: block.text });
      return;
    }
    const soul = cast.find((entry) => String(entry.name).toLowerCase() === String(block.speaker).toLowerCase());
    const leadIn = dialogueLeadIn(block.speaker, blocks[i - 1]);
    if (leadIn) raw.push({ voiceId: narratorVoiceId(), speaker: null, text: leadIn });
    raw.push({ voiceId: resolveVoiceId(soul, block.speaker), speaker: block.speaker, text: block.text });
  });
  const merged = [];
  for (const seg of raw) {
    const last = merged[merged.length - 1];
    if (last && last.voiceId === seg.voiceId && last.speaker === seg.speaker) {
      last.text = `${last.text} ${seg.text}`.trim();
    } else {
      merged.push({ ...seg });
    }
  }
  return merged;
}

// Back-compat: the flattened plain-text reading of a turn (used nowhere critical
// now, but kept stable for any external caller).
export function narrationText(dm, cast = []) {
  return narrationSegments(dm, cast).map((seg) => seg.text).join('\n\n');
}

const segmentKey = (campaignId, log, index, voiceId) =>
  `narration:${campaignId}:${log.recordHash || log.id}:${index}:${voiceId}`;

// Generate (or reuse) the audio for one voiced segment, WITH its provenance.
// Content-addressed in the same media table as painted assets so it survives
// reloads and export. The cache key includes the segment index and voice, so
// re-casting a voice or re-splitting a turn produces fresh audio instead of
// serving the old take.
export async function ensureSegmentAsset(campaign, log, segment, index) {
  if (!segment?.text) return null;
  const key = segmentKey(campaign.id, log, index, segment.voiceId);
  const cached = await db.media.where('cacheKey').equals(key).first();
  if (cached?.blob) return { blob: cached.blob, provider: cached.provider || 'unknown' };
  const response = await fetch('/api/speak', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ text: segment.text, voiceId: segment.voiceId }),
  });
  if (!response.ok) {
    const closed = await tollRefusal(response); // a 402 receipt reaches the patron
    throw new Error(closed?.error || `Narration failed (${response.status})`);
  }
  const blob = await response.blob();
  const provider = response.headers.get('X-Media-Provider') || 'unknown';
  try {
    const assetHash = await sha256(new Uint8Array(await blob.arrayBuffer()));
    await db.media.put({
      campaignId: campaign.id, kind: 'narration', cacheKey: key, assetHash,
      originTurnHash: log.recordHash || null, mime: blob.type, blob,
      provider, model: response.headers.get('X-Media-Model') || 'unknown',
      label: segment.speaker || 'narrator', variant: segment.voiceId, createdAt: Date.now(),
    });
  } catch { /* caching is best-effort; playback still works this session */ }
  return { blob, provider };
}

// Back-compat wrapper: just the blob.
export async function ensureSegmentBlob(campaign, log, segment, index) {
  const asset = await ensureSegmentAsset(campaign, log, segment, index);
  return asset?.blob || null;
}

let audio = null;    // the single live HTMLAudioElement for the active chain
let activeId = null;
let activeUrls = [];
let paused = false;  // OUR pause intent — the source of truth, not element.paused
                     // (an *ended* element also reports paused, which is why we
                     // must not infer pause state from the element)
let advancing = false; // true while the next segment is being generated (the
                       // inter-segment gap) so the button still reads "playing"
let session = 0;     // monotonic token; bumped on every stop/start so a slow
                     // generation that resolves after a newer request is discarded
const listeners = new Set();

function isPlaying() {
  return Boolean(activeId) && !paused && (advancing || Boolean(audio && !audio.paused && !audio.ended));
}

function emit() {
  const state = { id: activeId, playing: isPlaying() };
  // The Director's voice gate follows the reading as a whole: active from the
  // first request until stop/pause, spanning inter-segment gaps, so a music
  // phrase can never squeeze in between the narrator and a character's line.
  setVoiceActive(Boolean(activeId) && !paused);
  for (const fn of listeners) fn(state);
}

export function subscribeNarration(fn) {
  fn({ id: activeId, playing: isPlaying() });
  listeners.add(fn);
  return () => listeners.delete(fn);
}

// Retire an audio element completely: unwire it and stop it so it can never keep
// playing as an orphan once we've moved past it.
function retire(element) {
  if (!element) return;
  element.onended = null; element.onpause = null; element.onplay = null;
  try { element.pause(); } catch { /* jsdom/edge */ }
}

export function stopNarration() {
  session += 1; // invalidate any generation or segment advance still in flight
  retire(audio);
  activeUrls.forEach((url) => URL.revokeObjectURL(url));
  activeUrls = []; audio = null; activeId = null; paused = false; advancing = false;
  emit();
}

// Play one segment, then chain to the next on 'ended'. Event-driven (never
// awaits playback to finish) so the returned promise resolves as soon as the
// segment starts — a newer play/stop supersedes this chain via the session
// token, and a superseded chain never constructs an Audio element. Only ONE
// element is ever live: before starting a new segment we retire the previous
// one, and if the player paused during the gap we stage the segment without
// playing it, so two voices can never overlap. A segment of mock provenance is
// skipped entirely — better a silent beat than a placeholder tone.
async function playSegment(campaign, log, segments, index, mine) {
  if (mine !== session) return;
  if (index >= segments.length) { if (mine === session) stopNarration(); return; }
  advancing = true; // we are in the gap: generating the next segment
  let asset = null;
  try { asset = await ensureSegmentAsset(campaign, log, segments[index], index); } catch { asset = null; }
  if (mine !== session) return;                       // superseded while generating → drop
  if (!asset?.blob || asset.provider === 'mock') { await playSegment(campaign, log, segments, index + 1, mine); return; }
  const url = URL.createObjectURL(asset.blob); activeUrls.push(url);
  const element = new Audio(url);
  if (audio && audio !== element) retire(audio);      // never leave a prior segment live
  audio = element;
  element.onpause = emit; element.onplay = emit;
  element.onended = () => { if (mine === session) playSegment(campaign, log, segments, index + 1, mine); };
  advancing = false;
  if (mine !== session) { retire(element); return; }
  if (paused) { emit(); return; }                     // player paused in the gap: stage, don't play
  try { await element.play(); } catch { /* a browser may block autoplay until a tap */ }
  emit();
}

export async function playNarration(campaign, log, _options = {}) {
  stopNarration();
  const mine = session; // this call owns the narrator only while it stays current
  const segments = narrationSegments(log.dm, campaign.codex?.cast || []);
  if (!segments.length) return;
  activeId = log.id; paused = false;
  emit(); // claim the stage immediately: the Director silences music before the first word
  await playSegment(campaign, log, segments, 0, mine);
}

// Play/pause toggle for a specific turn's narration button. Pause/resume is
// driven by OUR `paused` flag, not the element's: during the inter-segment gap
// the current element has already ended (and so reports paused), and reading the
// element would wrongly resume a finished segment while the next one is loading —
// producing two voices. Instead we mark intent; a segment generated during a
// pause is staged (created but not played) and only starts on resume.
export function toggleNarration(campaign, log) {
  if (activeId === log.id && (audio || advancing)) {
    if (paused) {
      paused = false;
      if (audio && audio.paused && !audio.ended) audio.play().catch(() => {});
    } else {
      paused = true;
      if (audio && !audio.ended) audio.pause();
    }
    emit();
    return Promise.resolve();
  }
  return playNarration(campaign, log);
}
