import { db } from '../db.js';
import { sha256 } from '../canonical.js';
import { beatKeys } from './lookahead.js';
import { narratorVoiceId, castVoiceId, dialogueLeadIn } from './casting.js';

// ------------------------------------------------------------
// THE NARRATOR — the interactive-podcast voice. Each turn is read
// as a CAST performance: the storyteller narrator reads the prose
// and frames each line, then each character's OWN voice speaks
// their dialogue (never the narrator reading "Name: line"). The
// segments are generated by the server speak chain (ElevenLabs →
// mock), cached in Dexie per segment+voice, and played in sequence
// with the beat music ducked underneath. One turn plays at a time;
// a monotonic session token drops any generation that resolves
// after a newer request so two voices can never overlap. A tiny
// pub/sub lets per-turn buttons reflect play/pause. This bypasses
// the Foundry tier gate on purpose: hearing the story read aloud
// is a comfort setting, available at any media tier.
// ------------------------------------------------------------

// Break a turn into an ordered list of voiced segments. Narration (no speaker)
// is the narrator's; a line of dialogue becomes a short narrator lead-in that
// names the speaker, then the character's own voice reading only the line.
// Consecutive same-voice segments are merged so the narrator's stage-setting and
// its hand-off ("…and that is when Halvard said,") are one smooth clip.
export function narrationSegments(dm, cast = []) {
  const blocks = (dm?.narration_blocks || []).filter((block) => block && block.text);
  const raw = [];
  blocks.forEach((block, i) => {
    if (!block.speaker) {
      raw.push({ voiceId: narratorVoiceId(), speaker: null, text: block.text });
      return;
    }
    const soul = cast.find((entry) => String(entry.name).toLowerCase() === String(block.speaker).toLowerCase());
    const leadIn = dialogueLeadIn(block.speaker, blocks[i - 1]);
    if (leadIn) raw.push({ voiceId: narratorVoiceId(), speaker: null, text: leadIn });
    raw.push({ voiceId: castVoiceId(soul, block.speaker), speaker: block.speaker, text: block.text });
  });
  const merged = [];
  for (const seg of raw) {
    const last = merged[merged.length - 1];
    if (last && last.voiceId === seg.voiceId && last.speaker === seg.speaker) {
      last.text = `${last.text} ${seg.text}`.trim();
    } else {
      merged.push({ ...seg });
    }
  }
  return merged;
}

// Back-compat: the flattened plain-text reading of a turn (used nowhere critical
// now, but kept stable for any external caller).
export function narrationText(dm, cast = []) {
  return narrationSegments(dm, cast).map((seg) => seg.text).join('\n\n');
}

const segmentKey = (campaignId, log, index, voiceId) =>
  `narration:${campaignId}:${log.recordHash || log.id}:${index}:${voiceId}`;

// Generate (or reuse) the audio for one voiced segment. Content-addressed in the
// same media table as painted assets so it survives reloads and export. The
// cache key includes the segment index and voice, so re-casting a voice or
// re-splitting a turn produces fresh audio instead of serving the old take.
export async function ensureSegmentBlob(campaign, log, segment, index) {
  if (!segment?.text) return null;
  const key = segmentKey(campaign.id, log, index, segment.voiceId);
  const cached = await db.media.where('cacheKey').equals(key).first();
  if (cached?.blob) return cached.blob;
  const response = await fetch('/api/speak', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ text: segment.text, voiceId: segment.voiceId }),
  });
  if (!response.ok) throw new Error(`Narration failed (${response.status})`);
  const blob = await response.blob();
  try {
    const assetHash = await sha256(new Uint8Array(await blob.arrayBuffer()));
    await db.media.put({
      campaignId: campaign.id, kind: 'narration', cacheKey: key, assetHash,
      originTurnHash: log.recordHash || null, mime: blob.type, blob,
      provider: response.headers.get('X-Media-Provider') || 'unknown',
      model: response.headers.get('X-Media-Model') || 'unknown',
      label: segment.speaker || 'narrator', variant: segment.voiceId, createdAt: Date.now(),
    });
  } catch { /* caching is best-effort; playback still works this session */ }
  return blob;
}

// The music bed for a turn: its own beat stinger (matched by turn or by the
// lookahead-shared beat cache key), ducked under the voice during playback.
async function bedBlob(campaign, log) {
  const rows = await db.media.where('campaignId').equals(campaign.id).toArray();
  const music = rows.filter((row) => row.kind === 'music' && row.blob);
  if (!music.length) return null;
  const byTurn = music.filter((row) => log.recordHash && row.originTurnHash === log.recordHash)
    .sort((a, b) => b.createdAt - a.createdAt)[0];
  if (byTurn) return byTurn.blob;
  if (log.beatIndex != null) {
    const key = beatKeys(campaign.id, log.beatIndex).score;
    const found = music.find((row) => row.cacheKey === key);
    if (found) return found.blob;
  }
  return null;
}

let audio = null;    // the single live HTMLAudioElement for the active chain
let bed = null;      // HTMLAudioElement for the looped, ducked music bed
let activeId = null;
let activeUrls = [];
let paused = false;  // OUR pause intent — the source of truth, not element.paused
                     // (an *ended* element also reports paused, which is why we
                     // must not infer pause state from the element)
let advancing = false; // true while the next segment is being generated (the
                       // inter-segment gap) so the button still reads "playing"
let session = 0;     // monotonic token; bumped on every stop/start so a slow
                     // generation that resolves after a newer request is discarded
const listeners = new Set();

function isPlaying() {
  return Boolean(activeId) && !paused && (advancing || Boolean(audio && !audio.paused && !audio.ended));
}

function emit() {
  const state = { id: activeId, playing: isPlaying() };
  for (const fn of listeners) fn(state);
}

export function subscribeNarration(fn) {
  fn({ id: activeId, playing: isPlaying() });
  listeners.add(fn);
  return () => listeners.delete(fn);
}

// Retire an audio element completely: unwire it and stop it so it can never keep
// playing as an orphan once we've moved past it.
function retire(element) {
  if (!element) return;
  element.onended = null; element.onpause = null; element.onplay = null;
  try { element.pause(); } catch { /* jsdom/edge */ }
}

export function stopNarration() {
  session += 1; // invalidate any generation or segment advance still in flight
  retire(audio);
  if (bed) bed.pause();
  activeUrls.forEach((url) => URL.revokeObjectURL(url));
  activeUrls = []; audio = null; bed = null; activeId = null; paused = false; advancing = false;
  emit();
}

// Play one segment, then chain to the next on 'ended'. Event-driven (never
// awaits playback to finish) so the returned promise resolves as soon as the
// segment starts — a newer play/stop supersedes this chain via the session
// token, and a superseded chain never constructs an Audio element. Only ONE
// element is ever live: before starting a new segment we retire the previous
// one, and if the player paused during the gap we stage the segment without
// playing it, so two voices can never overlap.
async function playSegment(campaign, log, segments, index, mine) {
  if (mine !== session) return;
  if (index >= segments.length) { if (mine === session) stopNarration(); return; }
  advancing = true; // we are in the gap: generating the next segment
  let blob = null;
  try { blob = await ensureSegmentBlob(campaign, log, segments[index], index); } catch { blob = null; }
  if (mine !== session) return;                       // superseded while generating → drop
  if (!blob) { await playSegment(campaign, log, segments, index + 1, mine); return; }
  const url = URL.createObjectURL(blob); activeUrls.push(url);
  const element = new Audio(url);
  if (audio && audio !== element) retire(audio);      // never leave a prior segment live
  audio = element;
  element.onpause = emit; element.onplay = emit;
  element.onended = () => { if (mine === session) playSegment(campaign, log, segments, index + 1, mine); };
  advancing = false;
  if (mine !== session) { retire(element); return; }
  if (paused) { emit(); return; }                     // player paused in the gap: stage, don't play
  try { await element.play(); } catch { /* a browser may block autoplay until a tap */ }
  emit();
}

// Load and start the ducked music bed once, under the whole reading. Guarded so
// a superseded turn (or a reading the player paused before it loaded) never
// leaves an orphan loop playing.
async function startBed(campaign, log, mine) {
  const music = await bedBlob(campaign, log);
  if (!music || mine !== session || paused) return;
  const bedUrl = URL.createObjectURL(music); activeUrls.push(bedUrl);
  bed = new Audio(bedUrl); bed.loop = true; bed.volume = 0.16;
  bed.play().catch(() => { /* the voice still plays */ });
}

export async function playNarration(campaign, log, { withBed = true } = {}) {
  stopNarration();
  const mine = session; // this call owns the narrator only while it stays current
  const segments = narrationSegments(log.dm, campaign.codex?.cast || []);
  if (!segments.length) return;
  activeId = log.id; paused = false;
  const started = playSegment(campaign, log, segments, 0, mine);
  if (withBed) startBed(campaign, log, mine); // concurrent; ducked under the voice
  await started;
}

// Play/pause toggle for a specific turn's narration button. Pause/resume is
// driven by OUR `paused` flag, not the element's: during the inter-segment gap
// the current element has already ended (and so reports paused), and reading the
// element would wrongly resume a finished segment while the next one is loading —
// producing two voices. Instead we mark intent; a segment generated during a
// pause is staged (created but not played) and only starts on resume.
export function toggleNarration(campaign, log) {
  if (activeId === log.id && (audio || advancing)) {
    if (paused) {
      paused = false;
      if (audio && audio.paused && !audio.ended) audio.play().catch(() => {});
      bed?.play().catch(() => {});
    } else {
      paused = true;
      if (audio && !audio.ended) audio.pause();
      bed?.pause();
    }
    emit();
    return Promise.resolve();
  }
  return playNarration(campaign, log);
}
